// The cast of AI players. Each character maps to one of the three skill tiers
// and carries a personality: think-time rhythm, a bidding bias for the rookies
// and a handful of table-talk lines keyed by event.

export const ROSTER = [
  {
    id: 'rosie',
    name: 'Rosie',
    tier: 'rookie',
    stars: 1,
    tagline: 'Warm, chatty, plays by feel. Tends to underbid and collect bags.',
    think: [700, 1200],
    bidBias: -1,
    avatar: { bg: '#e8a0a8', skin: '#f3d1b5', hair: 'bun', hairColor: '#cfcfcf', glasses: 'round', accent: '#8a5a00', earrings: true },
    quips: {
      greeting: ['Oh, how lovely — a full table!', 'Deal me in, dear.'],
      bid: ['{n}, I think? Maybe.', 'Let’s say {n}. Fingers crossed!', 'I’ll try {n}, sweetheart.'],
      nil: ['Nothing at all for me. Nil!', 'These are tiny cards. Nil, please.'],
      won: ['Look at that, I won one!', 'Oh, was that mine?'],
      trumpedPartner: ['Oh dear, was that yours, partner?', 'Sorry! I got excited.'],
      set: ['Well, we tried.', 'Don’t you worry, we’ll get it next time.'],
      madeBid: ['We did it!', 'Lovely, just lovely.'],
      nilMade: ['Not a single trick — imagine that!'],
      nilBusted: ['Oh dear. Oh dear, oh dear.'],
      bagged: ['Are bags bad? They sound useful.'],
      oppSet: ['Oh, hard luck, dears.'],
      win: ['We won! Cookies for everyone.'],
      lose: ['Well played, you two.'],
    },
  },
  {
    id: 'benny',
    name: 'Benny',
    tier: 'rookie',
    stars: 1,
    tagline: 'Eager and impulsive. Overbids, leads aces, loves to trump.',
    think: [350, 650],
    bidBias: 1,
    avatar: { bg: '#5fa8d3', skin: '#c68a5a', hair: 'cap', hairColor: '#2b1d12', accent: '#ff7a3d' },
    quips: {
      greeting: ['Let’s go! I’m feeling lucky.', 'Shuffle up!'],
      bid: ['{n}. Easy.', 'I’ve got a good feeling about {n}!', '{n}! No, wait — yeah, {n}.'],
      nil: ['Nil. Vibes say nil.'],
      won: ['Boom!', 'Called it.', 'That’s mine!'],
      trumpedPartner: ['Oops. Team effort, right?', 'My bad, partner.'],
      set: ['That was rigged.', 'Ugh. Next hand.'],
      madeBid: ['Told you.', 'Easy money.'],
      nilMade: ['Zero! Nothing! Nada!'],
      nilBusted: ['Wait, that counts against us?'],
      bagged: ['So bags are… bad. Got it.'],
      oppSet: ['Ha! Set!'],
      win: ['GG! We’re unstoppable.'],
      lose: ['Rematch. Right now.'],
    },
  },
  {
    id: 'marcus',
    name: 'Marcus',
    tier: 'solid',
    stars: 2,
    tagline: 'Tidy club player. Bids honestly, hates bags, ducks under a winning partner.',
    think: [600, 1000],
    avatar: { bg: '#2e8b57', skin: '#8d5a3b', hair: 'short', hairColor: '#1b1b1f', glasses: 'square', accent: '#e8e8e8', mustache: true },
    quips: {
      greeting: ['Good table. Let’s keep it tidy.'],
      bid: ['{n}.', '{n}, nice and steady.', 'I can see {n}.'],
      nil: ['Nil. I’ll stay out of the way.'],
      won: ['Noted.', 'That’s one.'],
      set: ['Hm. Off by one.', 'That’s on me.'],
      madeBid: ['Right on the number.'],
      madeBidClean: ['Bid made, no bags.', 'Right on the number.'],
      nilMade: ['Clean nil.'],
      nilBusted: ['That one got away from me.'],
      bagged: ['Bags. I warned you.'],
      oppSet: ['That’s a set.'],
      partnerBagged: ['Careful, partner — that’s a bag.'],
      win: ['Solid game.'],
      lose: ['Well bid. Well played.'],
    },
  },
  {
    id: 'dee',
    name: 'Dee',
    tier: 'solid',
    stars: 2,
    tagline: 'Competitive league regular. Honest bids, good instincts, a little chatty.',
    think: [500, 900],
    avatar: { bg: '#b57edc', skin: '#f1c9a5', hair: 'bob', hairColor: '#8a2e2e', earrings: true },
    quips: {
      greeting: ['Let’s make this interesting.'],
      bid: ['{n}. Book it.', 'I’m good for {n}.', '{n} and not a trick more.'],
      nil: ['Going nil. Cover me.'],
      won: ['Mine.', 'Thank you very much.'],
      set: ['We’ll get it back.', 'One short. Annoying.'],
      madeBid: ['Bid made.', 'Like clockwork.'],
      nilMade: ['Nil made. Cover appreciated.'],
      nilBusted: ['No! That was so close.'],
      bagged: ['Ugh, bags.'],
      oppSet: ['Set! Love it.'],
      win: ['That’s how it’s done.'],
      lose: ['Good game. Run it back?'],
    },
  },
  {
    id: 'vega',
    name: 'Vega',
    tier: 'expert',
    stars: 3,
    tagline: 'Cool card shark. Counts every spade, sets bids, and feeds you bags.',
    think: [900, 1500],
    avatar: { bg: '#ff7a5c', skin: '#e0ac7c', hair: 'slick', hairColor: '#111', glasses: 'sun', accent: '#111' },
    quips: {
      greeting: ['Sit down. This won’t take long.'],
      bid: ['{n}.', '{n}. Exactly.', 'Say {n}.'],
      nil: ['Nil.'],
      won: [],
      set: ['Unusual.', 'Noted.'],
      madeBid: ['As planned.'],
      nilMade: ['Naturally.'],
      nilBusted: ['That was your one chance.'],
      bagged: ['A bag, on the house.', 'Enjoy the bag.'],
      oppSet: ['Set. You bid too high.'],
      spadesGone: ['That’s the last spade.'],
      win: ['Predictable.'],
      lose: ['Well. That happens once.'],
    },
  },
  {
    id: 'okafor',
    name: 'Prof. Okafor',
    tier: 'expert',
    stars: 3,
    tagline: 'Patient, precise, and generous with card-counting facts.',
    think: [1000, 1600],
    avatar: { bg: '#3a6ea5', skin: '#6b3f25', hair: 'bald', hairColor: '#e8e8e8', glasses: 'round', accent: '#ffd166', beard: true },
    quips: {
      greeting: ['A pleasure. Let’s think carefully.'],
      bid: ['{n}, by my count.', 'The hand suggests {n}.', '{n}.'],
      nil: ['I shall attempt nil.'],
      won: ['As expected.'],
      set: ['An instructive hand.'],
      madeBid: ['Precisely.'],
      nilMade: ['Zero tricks. Quite satisfying.'],
      nilBusted: ['A miscalculation on my part.'],
      bagged: ['Bags accumulate quietly, then all at once.'],
      oppSet: ['One trick short. It happens.'],
      spadesGone: ['Every spade is accounted for.'],
      win: ['Well reasoned, all.'],
      lose: ['Congratulations. Genuinely.'],
    },
  },
  {
    id: 'sable',
    name: 'Sable',
    tier: 'expert',
    stars: 3,
    tagline: 'Quiet and ruthless. Says almost nothing; misses almost nothing.',
    think: [800, 1300],
    avatar: { bg: '#4a4e69', skin: '#f1d3b8', hair: 'long', hairColor: '#1b1b1f', smile: false },
    quips: {
      greeting: ['…'],
      bid: ['{n}.'],
      nil: ['Nil.'],
      won: [],
      set: ['Hm.'],
      madeBid: [],
      nilMade: ['Done.'],
      nilBusted: ['Tch.'],
      bagged: [],
      oppSet: ['Set.'],
      win: ['Good.'],
      lose: ['Again.'],
    },
  },
];

export const ROSTER_BY_ID = Object.fromEntries(ROSTER.map((b) => [b.id, b]));

/** Preset tables. Seat roles: partner = North (seat 2), west = seat 1, east = seat 3. */
export const PRESETS = {
  casual: {
    label: 'Casual',
    blurb: 'A friendly table. Solid partner, two rookies to learn against.',
    lineup: { partner: 'marcus', west: 'rosie', east: 'benny' },
  },
  standard: {
    label: 'Standard',
    blurb: 'A mixed table: a rookie, a solid partner and one expert to watch out for.',
    lineup: { partner: 'marcus', west: 'rosie', east: 'vega' },
  },
  hard: {
    label: 'Hard',
    blurb: 'The pro table. Expert partner, two expert opponents.',
    lineup: { partner: 'okafor', west: 'vega', east: 'sable' },
  },
};

export const TIER_LABEL = { rookie: 'Rookie', solid: 'Solid', expert: 'Expert' };

/** Map a lineup {partner, west, east} to characters by seat (seat 0 = human = null). */
export function lineupBySeat(lineup) {
  return [null, ROSTER_BY_ID[lineup.west], ROSTER_BY_ID[lineup.partner], ROSTER_BY_ID[lineup.east]];
}
